name: Build Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust and Windows target
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup target add x86_64-pc-windows-gnu
    
    - name: Build
      run: |
        source $HOME/.cargo/env
        cargo build --release --target x86_64-pc-windows-gnu
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: program.exe
        path: target/x86_64-pc-windows-gnu/release/simple-rust.exe
